FROM arching AS archliquidprompt
MAINTAINER me

RUN echo "git clone https://github.com/neo4j/neo4j.git" > /root/largegit.sh

RUN git clone --branch stable https://github.com/nojhan/liquidprompt.git /root/liquidprompt
RUN echo "[[ \$- = *i* ]] && source /root/liquidprompt/liquidprompt" >> /root/.bashrc 
RUN echo "[[ \$- = *i* ]] && source /root/liquidprompt/liquidprompt" >> /root/.zshrc 
RUN echo "liquidprompt" > /root/prompt.txt

